prefer_labels = true # if true, have labels override categories
ignore_categories = [
    "Credit Card Payment",
    "ATM Fee",
]


[paths]
use_custom_input = true
input_file = "/home/YourName/budgets/your_transactions.csv"

use_custom_output = false
# output_path = "/home/somewhere/else"




############## WARNING ##############
# Make sure not to commit or share anything personal here!
# All numbers here are assumed to be biweekly
# Please scale by the appropriate factor if not
[paycheck]
net_earnings = 1000

    #### add as many key-value pairs as you have
    [paycheck.pretax]
    "Federal Income Tax" = 100
    "Social Security" = 30
    "Medicare" = 50
    "State Income Tax" = 50
    # "Health Insurance" = 1
    # "Dental Insurance" = 2
    # "Vision Insurance" = 3
    # "401k" = 401
