[time]
# Dates should be in MM/DD/YYYY format, with optional leading zeros
start_date = "5/1/2018"
end_date = "8/1/2018"

[transactions]
prefer_labels = true # have labels override categories
use_percentages = false # output in relative percentages

# Vendors to ignore
ignore_vendors = [
    "Bad Vendor"
]

# Categories to ignore
ignore_categories = [
    "Bad Category",
]

# Mint is a bit verbose on the categories by default, so
# any category with a sumnmed value below the threshold
# will get bundled as 'Misc'
category_threshold = 15

[paths]
use_custom_input = true
input_file = "data/test-data.csv"

use_custom_output = false
output_path = "output-test.txt"

############## WARNING ##############
# Make sure not to commit or share anything personal here!
# All numbers here are assumed to be biweekly
# Please scale by the appropriate factor if not
[paycheck]
net_earnings = 150

    #### add as many key-value pairs as you have
    [paycheck.pretax]
    "Federal Income Tax" = 30
    "Social Security" = 5
